---
kind: pipeline
type: exec
name: cronRebase

platform:
  os: linux
  arch: amd64

trigger:
    branch:
        include:
            - master

steps:
  - name: sync repo
    commands:
      - git remote add upstream https://github.com/massgravel/Microsoft-Activation-Scripts.git
      - git fetch upstream
      - git rebase upstream/master
      - git remote set-url origin git@github.com:dangherve/Microsoft-Activation-Scripts.git
      - git push --force --set-upstream origin master

---
kind: pipeline
type: exec
name: rebase

platform:
  os: linux
  arch: amd64

trigger:
    branch:
        exclude:
            - master

steps:
  - name: sync repo
    commands:
      - git remote add upstream https://github.com/massgravel/Microsoft-Activation-Scripts.git
      - git fetch
      - git checkout master
      - git fetch upstream
      - git rebase upstream/master
      - git remote set-url origin git@github.com:dangherve/Microsoft-Activation-Scripts.git
      - git push --force --set-upstream origin master

